-- SUPABASE SETUP — Mahmoud & Nourhan Guest Wishes
-- Run this once in Supabase SQL Editor.

create table if not exists public.wishes (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  message text not null check (char_length(message) between 1 and 500),
  approved boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.wishes enable row level security;

-- Visitors can see approved wishes.
drop policy if exists "Anyone can read approved wishes" on public.wishes;
create policy "Anyone can read approved wishes"
on public.wishes
for select
to anon
using (approved = true);

-- Visitors can submit a wish.
drop policy if exists "Anyone can submit wishes" on public.wishes;
create policy "Anyone can submit wishes"
on public.wishes
for insert
to anon
with check (
  approved = true
  and char_length(name) between 1 and 60
  and char_length(message) between 1 and 500
);

create index if not exists wishes_created_at_idx
on public.wishes (created_at desc);
